apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  labels:
    application: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.21.4
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - name: htmldir
        mountPath: /var/log/nginx
      - name: nginx-conf
        mountPath: "/etc/nginx/"
        readOnly: true
    - name: fluentd
      image: fluentd:v1.14-1
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - name: htmldir
        mountPath: /logs
      - name: fluent-conf
        mountPath: "/fluentd/etc"
        readOnly: true
  volumes:
    - name: htmldir
      emptyDir: {}
    - name: nginx-conf
      configMap:
        name: nginx-conf
    - name: fluent-conf
      configMap:
        name: fluent-conf
