apiVersion: v1
kind: Pod
metadata:
  name: pod-wordpress
  labels:
    application: wordpress
spec:
  containers:
    - name: wordpress
      image: wordpress:5.9.2
      imagePullPolicy: IfNotPresent
      env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            secretKeyRef:
              name: secret-mssql
              key: DATABASE_HOST
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: secret-mssql
              key: DATABASE_USER
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-mssql
              key: DATABASE_PASSWORD
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: secret-mssql
              key: DATABASE_NAME
      resources:
        requests:
          memory: "125Mi"
          cpu: "250m"
        limits:
          memory: "256Mi"
          cpu: "250m"
      livenessProbe:
        initialDelaySeconds: 60
        httpGet:
          path: /
          port: 80
        periodSeconds: 10
        timeoutSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      readinessProbe:
        initialDelaySeconds: 30
        httpGet:
          path: /
          port: 80
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
        successThreshold: 1
