apiVersion: v1
kind: Pod
metadata:
  name: pod-mysql
  labels:
    application: mysql
spec:
  containers:
    - name: mysql
      image: mysql:8.0.28
      imagePullPolicy: IfNotPresent
      env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: secret-mssql
            key: DATABASE_ROOT_PASSWORD
      - name: MYSQL_USER
        valueFrom:
          secretKeyRef:
            name: secret-mssql
            key: DATABASE_USER
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: secret-mssql
            key: DATABASE_PASSWORD
      - name: MYSQL_DATABASE
        valueFrom:
          secretKeyRef:
            name: secret-mssql
            key: DATABASE_NAME
      resources:
        requests:
          memory: "516Mi"
          cpu: "250m"
        limits:
          memory: "1024Mi"
          cpu: "250m"
      ports:
      - containerPort: 3306
        name: mysql
        protocol: TCP
