apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
spec:
  selector:
    application: nginx
  ports:
    - port: 8888
      targetPort: 80
  type: LoadBalancer
---

apiVersion: v1
kind: Service
metadata:
  name: svc-wordpress
spec:
  selector:
    application: wordpress
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---

apiVersion: v1
kind: Service
metadata:
  name: svc-mysql
spec:
  selector:
    application: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
